### ISSUE TITLE
deprecated elasticsearch plugin 2.4.5

### ISSUE THREAD

**Issue by christiangierschner** [obiba/docker-opal#27] opened 2023-05-15 14:30 UTC
Hi...

recently there was a elasticsearch CVE...i then checked all elasticsearch occurences in our environment and found a very very old elasticsearch version (2.4.5) in our recent OPAL server (4.5.8)

in your installation [docs](https://opaldoc.obiba.org/en/latest/admin/plugins.html#automatic-installation) you say:
```Because having a search engine is an absolute requirement, Opal server will check at startup that there is a plugin of type opal-search and if it’s not the case, the latest version of the [opal-search-es](https://github.com/obiba/opal-search-es/releases) plugin (that applies to the current Opal server version) will be automatically downloaded and installed without needing a server restart. If for any reason this plugin cannot be automatically downloaded (network issue), the Opal start-up will fail and you will need to install the plugin manually.```

this is the [line](https://github.com/obiba/docker-opal/blob/dab3dc6b9db151e4fbff3322de6d3278f99191b4/Dockerfile#L107) from your Dockerfile in which you install opal-search-es

The [Plugin](https://github.com/obiba/opal-search-es) itself was last updated 2 years ago...

Could you please update all of your plugins to the most recent safe-to-use versions because of the requirement that a deprecated search plugin has to be installed in the server deployment...

Or remove the opal-search-es dependency...

**Comment by ymarcon** [comment] 2023-05-15 16:04
Yes we know that... The problem is that since ES5 (that just followed 2.4), ES could not be embedded in a java application anymore. We could have done like with Mica: abstract the ES API and make a plugin for higher versions of ES but some of the search features opal is using have been removed. There is quite some refactoring work then.

**Comment by christiangierschner** [comment] 2023-05-24 14:17
so, remove the automatic install and the dependency or does opal just not work without opel-search-es?

**Comment by ymarcon** [comment] 2024-08-30 10:21
Fixed by obiba/opal#3893

**Closed by ymarcon** 2024-08-30 10:21 UTC
